version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: dockertest
      MYSQL_ROOT_PASSWORD: wnsgk123
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - 6380:6379
    restart: always

  app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysql
    restart: always